  import * as React from "react";

  const MOBILE_BREAKPOINT = 768;

  export function useIsMobile() {
    const [isMobile, setIsMobile] = React.useState<boolean | undefined>(undefined);

      React.useEffect(() => {
        const mql = window.matchMedia(`(max-width: ${MOBILE_BREAKPOINT - 1}px)`);
        const onChange = () => {
          setIsMobile(window.innerWidth < MOBILE_BREAKPOINT);
        };
        mql.addEventListener("change", onChange);
        setIsMobile(window.innerWidth < MOBILE_BREAKPOINT);
        return () => mql.removeEventListener("change", onChange);
      }, []);

      return !!isMobile;
  }




9. Notes & gotchas
    Never ship SUPABASE_SERVICE_ROLE_KEY to the browser; it is only read inside server handlers.
     src/routeTree.gen.ts is generated by the router plugin — do not author it; it appears after the first dev/build run.
    IMAP libraries such as imapflow break on Worker runtimes; that is exactly why imap-lite.server.ts exists. Keep it.
    Assets must be imported as ES modules from src/assets (not referenced by string path) so Vite hashes them — otherwise
    images break on Vercel.
    Set PUBLIC_BASE_URL in src/lib/public-base.ts to your own domain, or leave "" for auto-detect from the request host.
    Order IDs are 10-digit random numbers; the public pay endpoint returns only render-safe columns.
